name: Restful Booker API Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: Restful-Booker-Interview-API-Project
        run: npm install

      - name: Run Newman tests
        working-directory: Restful-Booker-Interview-API-Project
        run: npm test

